language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.1.1
    - android-19

env:
  global:
    - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
    - ANDROID_SDKS=android-14
    - ANDROID_TARGET=android-14

script:
  - mv WordPressEditor/src/androidTest/java/android/support/v4/widget/DrawerLayoutImpl.file WordPressEditor/src/androidTest/java/android/support/v4/widget/DrawerLayoutImpl.java
  - ./gradlew -PdisablePreDex build
